version: '3.8'
#define docker containers that i want to run
services:
  db-prisma:
    image: postgres:13
    #exported on port 5434, if we connect to postgres 5434 on our pc, we will be able access it
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks: 
      - api_net

networks:
  api_net:
